version: "3.9"
services:
  api:
    build: .
    container_name: flypro_api
    env_file: .env
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
  postgres:
    image: postgres:15
    container_name: flypro_pg
    environment:
      POSTGRES_DB: flypro
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    image: redis:7
    container_name: flypro_redis
    ports:
      - "6379:6379"
volumes:
  pgdata:
